Accounts/urls.py
import profile
from django.urls import path
from .views import *



app_name = 'accounts'

urlpatterns =[
    path('home/',home, name='home_page'),
    path('users/auth/register/account/',register_User, name='register_account'),
    path('users/hod/auth/register/account/',register_Hod, name='register_hod_account'),
    path('verify/',verify_view, name='verify_user'),
    path('login/', auth_view, name='login'),
    path('hod/login/', hod_auth_view, name='hod_login'),
    path('user/profile/entry/',profile_entry, name='user_profile'),
    path('student/auth/login/', student_auth_view, name="student_login"),
    path('student/auth/signup/',register_Student, name="student_signup"),
    
]

Exam_Scheduling_System/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Management.urls',namespace='management')),
    path('scheduling/',include('Scheduling.urls',namespace='scheduling')),
    path('accounts/',include('Accounts.urls',namespace='accounts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Accounts/models.py
from django.db import models
from django.contrib.auth.models import User
import random
from Database.models import Department

# Create your models here.

levels = (
    ('Admins','Admins'),('Staff','Staff'),('hod','hod')
)
sex =(
    ('Male','Male'),('Female','Female')
)

class Staff(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    ec_number = models.CharField(max_length=8)
    gender = models.CharField(max_length=100,choices=sex)
    access_level = models.CharField(max_length=100, choices=levels)
    def __str__(self):return self.first_name

class Hod(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    ec_number = models.CharField(max_length=8)
    gender = models.CharField(max_length=100,choices=sex)
    department = models.OneToOneField(Department, on_delete=models.CASCADE, related_name='department_hod')

class Codes(models.Model):
    code = models.CharField(max_length=5)
    user = models.OneToOneField(User, on_delete=models.CASCADE,related_name='user_code')

    def __str__(self): return self.code

    # generate a random code to validate the user when login
    def save(self, *args, **kwargs):
        number_list = [x for x in range(10)]
        code_items =[]

        for i in range(5):
            num = random.choice(number_list)
            code_items.append(num)

        code_string = "".join(str(item) for item in code_items)
        self.code = code_string 
        super().save(*args, **kwargs)

Accounts/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm

import re

from Database.models import Student
from .models import Codes, Staff,Hod

#forms
class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control signup-name','Label':'Username:','Placeholder':'Username'}))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'form-control signin-password',
            'id': 'password',
            'Placeholder':'Your password'
        }
    ))

class StaffSignUp(UserCreationForm):
    class Meta:
        model=User
        fields = ['username','first_name','password1','password2']

    def clean_username(self):
        username = self.cleaned_data['username']
        r = User.objects.filter(username=username)
        applicant = Staff.objects.filter(ec_number = username)
        if r.count():
            raise forms.ValidationError("Username already exists")
        if not applicant.count():
            raise forms.ValidationError("Your EC Number is not recognised!")
        return username

    def clean_first_name(self):
        phone_number = self.cleaned_data['first_name']
        mobile_number_format = re.compile(r"^[7]\d{8}$")
        pattern = mobile_number_format.search(str(phone_number))
        if not pattern:
            raise ValidationError('Invalid Mobile Number!')
        return phone_number

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password1'] != cd['password2']:
            raise forms.ValidationError('Passwords do not match.')
        return cd['password2']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update(
            {'class': 'form-control signup-name','placeholder':'Enter EC Number'})
        self.fields['first_name'].widget.attrs.update(
            {'class': 'form-control signup-number','placeholder':'Enter Phone Number'})
        self.fields['password1'].widget.attrs.update(
            {'class': 'form-control signup-password','placeholder':'Enter Password'})
        self.fields['password2'].widget.attrs.update(
            {'class': 'form-control signup-password','placeholder':'Confirm Password'})

class CodeForm(forms.ModelForm):
    code = forms.CharField(max_length=5)

    class Meta:
        model = Codes
        fields = ('code',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['code'].widget.attrs.update(
            {'class': 'form-control signup-name','placeholder':'Enter the code.'})

class HodSignUp(UserCreationForm):
    class Meta:
        model=User
        fields = ['username','first_name','password1','password2']

    def clean_username(self):
        username = self.cleaned_data['username']
        r = User.objects.filter(username=username)
        applicant = Hod.objects.filter(ec_number = username)
        if r.count():
            raise forms.ValidationError("Username already exists")
        if not applicant.count():
            raise forms.ValidationError("Your EC Number is not recognised!")
        return username

    def clean_first_name(self):
        phone_number = self.cleaned_data['first_name']
        mobile_number_format = re.compile(r"^07\d{8}$")
        pattern = mobile_number_format.search(str(phone_number))
        if not pattern:
            raise ValidationError('Invalid Mobile Number!')
        return phone_number

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password1'] != cd['password2']:
            raise forms.ValidationError('Passwords do not match.')
        return cd['password2']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update(
            {'class': 'form-control signup-name','placeholder':'Enter EC Number'})
        self.fields['first_name'].widget.attrs.update(
            {'class': 'form-control signup-number','placeholder':'Enter Phone Number'})
        self.fields['password1'].widget.attrs.update(
            {'class': 'form-control signup-password','placeholder':'Enter Password'})
        self.fields['password2'].widget.attrs.update(
            {'class': 'form-control signup-password','placeholder':'Confirm Password'})

class StudentSignUp(UserCreationForm):
    class Meta:
        model=User
        fields = ['username','first_name','password1','password2']

    def clean_username(self):
        username = self.cleaned_data['username']
        r = User.objects.filter(username=username)
        applicant = Student.objects.filter(reg_number = username)
        if r.count():
            raise forms.ValidationError("Reg number already exists")
        if not applicant.count():
            raise forms.ValidationError("Your Student ID is not recognised!")
        return username

    def clean_first_name(self):
        phone_number = self.cleaned_data['first_name']
        mobile_number_format = re.compile(r"^07\d{8}$")
        pattern = mobile_number_format.search(str(phone_number))
        if not pattern:
            raise ValidationError('Invalid Mobile Number!')
        return phone_number

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password1'] != cd['password2']:
            raise forms.ValidationError('Passwords do not match.')
        return cd['password2']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update(
            {'class': 'form-control signup-name','placeholder':'Enter Student ID'})
        self.fields['first_name'].widget.attrs.update(
            {'class': 'form-control signup-number','placeholder':'Enter Phone Number'})
        self.fields['password1'].widget.attrs.update(
            {'class': 'form-control signup-password','placeholder':'Enter Password'})
        self.fields['password2'].widget.attrs.update(
            {'class': 'form-control signup-password','placeholder':'Confirm Password'})

Accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login
from django.contrib.auth.models import User
from django.contrib.auth.models import Group
from django.urls import reverse
from django.contrib import messages
from django.http import HttpResponseRedirect

from .models import *
from .forms import *
from .utils import send_sms

@login_required
def home(request):
    return render(request, 'home.html')

def is_admin(user):
    return user.groups.filter(name='Admins').exists()
def is_staff(user):
    return user.groups.filter(name='Staff').exists()

def is_hod(user):
    return user.groups.filter(name='hod').exists()

def is_student(user):
    return user.groups.filter(name='Students').exists()

#entry page for every user
def profile_entry(request):
    if is_staff(request.user):
        return redirect('management:get_programmes')
    elif is_hod(request.user):
        return redirect('management:department_timetable')
    elif is_student(request.user):
        return redirect('management:student_prof')
    elif is_admin(request.user):
        return redirect('admin:index')


def register_User(request):
    if request.method =='POST':
        form = StaffSignUp(request.POST)
        username = request.POST.get('username')
        if form.is_valid():
            member = Staff.objects.get(ec_number = username)
            #get the group where the user was assigned
            group  = Group.objects.get(name=member.access_level)
            user = form.save()
            #add user to the group
            group.user_set.add(user)
            return redirect('accounts:login')
    else:
        form = StaffSignUp()
    return render(request,'accounts/signup.html',{'form':form})

def register_Hod(request):
    if request.method =='POST':
        form = HodSignUp(request.POST)
        username = request.POST.get('username')
        if form.is_valid():
            member = Hod.objects.get(ec_number = username)
            group  = Group.objects.get(name="hod")
            user = form.save()
            group.user_set.add(user)
            return redirect('accounts:login')
    else:
        form = HodSignUp()
    return render(request,'accounts/hod-signup.html',{'form':form})

def register_Student(request):
    if request.method =='POST':
        form = StudentSignUp(request.POST)
        if form.is_valid():
            group  = Group.objects.get(name="Students")
            user = form.save()
            group.user_set.add(user)
            return redirect('accounts:student_login')
    else:
        form = StudentSignUp()
    return render(request,'accounts/student-signup.html',{'form':form})

#authenticate user
def auth_view(request):
    form = UserLoginForm()
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        #if user enters correct credential 
        # redirect the user to the code verification form
        if user is not None:
            request.session['pk'] = user.id
            return redirect('accounts:verify_user')
        else:
            messages.error(request,"Invalid username and or password!")
            return HttpResponseRedirect(reverse('accounts:login'))

    return render(request, 'accounts/login.html',{'form':form})

def hod_auth_view(request):
    form = UserLoginForm()
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            request.session['pk'] = user.id
            return redirect('accounts:verify_user')
        else:
            messages.error(request,"Invalid username and or password!")
            return HttpResponseRedirect(reverse('accounts:hod_login'))

    return render(request, 'accounts/hod-login.html',{'form':form})

def student_auth_view(request):
    form = UserLoginForm()
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            request.session['pk'] = user.id
            return redirect('accounts:verify_user')
        else:
            messages.error(request,"Invalid username and or password!")
            return HttpResponseRedirect(reverse('accounts:student_login'))

    return render(request, 'accounts/student-login.html',{'form':form})

def verify_view(request):
    form = CodeForm(request.POST or None)
    pk = request.session.get('pk')
    if pk:
        user = User.objects.get(pk=pk)
        code = user.user_code
        code_user = f"{user.username}:{user.user_code}"
        if not request.POST:
            print(code_user)
            #send SMS
            #first name represent phone_numner
            #did not want to override user
            number = "+263"+ str(user.first_name)
            send_sms(number,code_user)

        if form.is_valid():
            num = form.cleaned_data.get('code')

            if str(code) == num:
                code.save()
                login(request, user)
                return redirect('accounts:user_profile')
            else:
                messages.error(request,"Invalid authentication code")
                return HttpResponseRedirect(reverse('accounts:verify_user'))
        
    return render(request, 'accounts/codes.html',{'form':form})

templates/accounts/codes.html
{% load static %}
<!DOCTYPE html>
<html lang="en"> 
<head>
    <title>MSUAS | Authentication Code</title>
    
    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <meta name="description" content="MSUAS EXAMINATION SYSTEM">
    <meta name="author" content="SAMSON FUKUZEYA">    
    <link rel="shortcut icon" href="favicon.ico"> 
    
    <!-- FontAwesome JS-->
    <script defer src="{% static 'assets/plugins/fontawesome/js/all.min.js' %}"></script>
    
    <!-- App CSS -->  
    <link id="theme-style" rel="stylesheet" href="{% static 'assets/css/portal.css' %}">

</head> 

<body class="app app-reset-password p-0">    	
    <div class="row g-0 app-auth-wrapper">
	    <div class="col-12 col-md-12 col-lg-12 auth-main-col text-center p-5">
		    <div class="d-flex flex-column align-content-end">
			    <div class="app-auth-body mx-auto">	
				    <div class="app-auth-branding mb-4"><a class="app-logo" href="/"><img class="logo-icon me-2" src="{% static 'logo-icon.png' %}" alt="logo"></a></div>
					<h2 class="auth-heading text-center mb-4">Two Factor Authentication Code</h2>

					<div class="auth-intro mb-4 text-center">Enter the code sent to your phone number.</div>
	
					<div class="auth-form-container text-left">
						{% if messages %}
						{% for message in messages %}
						{% if message.tags == 'error' %}
						<div class="alert alert-danger" style="margin-top:10px">{{ message }}</div>
						{% endif %}
						{% if message.tags == 'success' %}
						<div class="alert alert-success" style="margin-top:10px">{{ message }}</div>
						{% endif %}
						{% endfor %}
						{% endif %}
						<form class="auth-form resetpass-form" method="post"> {% csrf_token %}
							<div class="email mb-3">
								<label class="sr-only" for="reg-email">Authentication Code</label>
								{{form.code}}
							</div><!--//form-group-->
							<div class="text-center">
								<button type="submit" class="btn app-btn-primary btn-block theme-btn mx-auto">Verify Code</button>
							</div>
						</form>
						
						<div class="auth-option text-center pt-5"><a class="app-link" href="{% url 'accounts:login' %}" >Log in</a> <span class="px-2">|</span> <a class="app-link" href="{% url 'accounts:register_account' %}" >Sign up</a></div>
					</div><!--//auth-form-container-->


			    </div><!--//auth-body-->
		    
			    <footer class="app-auth-footer">
				    <div class="container text-center py-3">
				         <!--/* This template is free as long as you keep the footer attribution link. If you'd like to use the template without the attribution link, you can buy the commercial license via our website: themes.3rdwavemedia.com Thank you for your support. :) */-->
			        <small class="copyright">Developed by Samson Fukuzeya <i class="fas fa-heart" style="color: #fb866a;"></i> @msuas 2022 Projects </small>
				       
				    </div>
			    </footer><!--//app-auth-footer-->	
		    </div><!--//flex-column-->   
	    </div><!--//auth-main-col-->

    </div><!--//row-->


</body>
</html> 

templates/accounts/hod-login.html
{% load static %}
<!DOCTYPE html>
<html lang="en"> 
<head>
    <title>MSUAS | Sign In</title>
    
    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <meta name="description" content="Examination Scheduling System">
    <meta name="author" content="Samson Fukuzeya">    
    
    <!-- FontAwesome JS-->
    <script defer src="{% static 'assets/plugins/fontawesome/js/all.min.js' %}"></script>
    
    <!-- App CSS -->  
    <link id="theme-style" rel="stylesheet" href="{% static 'assets/css/portal.css' %}">

</head> 

<body style="background-color: rgb(222, 109, 109);">    	
    <div class="row g-0 app-auth-wrapper">
	    <div class="col-12 col-md-12 col-lg-12 auth-main-col text-center p-5">
		    <div class="d-flex flex-column align-content-end">
			    <div class="app-auth-body mx-auto">	
				    <div class="app-auth-branding mb-4"><a class="app-logo" href="/"><img class="logo-icon me-2" src="{% static 'logo-icon.png' %}" alt="logo"></a></div>
					<h2 class="auth-heading text-center mb-5">Log in to Portal</h2>
			        <div class="auth-form-container text-start">
						{% if form.errors %}
                        <h4 class="alert alert-danger">Wrong password or username!</h4>
                        {% for field in form %}
                        {% if field.errors %}
                        <div class="alert alert-box alert-danger" role="alert">
                            <h3>Wrong username or Password!</h3>
                        </div>
                        {% endif %}
                        {% endfor %}
                        {% endif %}
						{% if messages %}
                            {% for message in messages %}
                            {% if message.tags == 'error' %}
                            <div class="alert alert-danger" style="margin-top:10px">{{ message }}</div>
                            {% endif %}
                            {% if message.tags == 'success' %}
                            <div class="alert alert-success" style="margin-top:10px">{{ message }}</div>
                            {% endif %}
                            {% endfor %}
                          {% endif %}
						<form class="auth-form login-form" method="post">{% csrf_token %}         
							<div class="email mb-3">
								<label class="sr-only" for="signup-email">Your EC Number</label>
								{{form.username}}
							</div>
							<div class="password mb-3">
								<label class="sr-only" for="signup-password">Password</label>
								{{form.password}}
							</div>
								<div class="extra mt-3 row justify-content-between">
									<div class="col-6">
										<div class="form-check">
											<input class="form-check-input" type="checkbox" value="" id="RememberPassword">
											<label class="form-check-label" for="RememberPassword">
											Remember me
											</label>
										</div>
									</div><!--//col-6-->
									<div class="col-6">
										<div class="forgot-password text-end">
											<a href="reset-password.html">Forgot password?</a>
										</div>
									</div><!--//col-6-->
								</div><!--//extra-->
							</div><!--//form-group-->
							<div class="text-center">
								<button type="submit" class="btn w-100 theme-btn mx-auto" style="background-color: brown;">Log In</button>
							</div>
						</form>
						
						<div class="auth-option text-center pt-5">No Account? Sign up <a class="text-link" href="{% url 'accounts:register_hod_account' %}" >here</a>.</div>
					</div><!--//auth-form-container-->	

			    </div><!--//auth-body-->
		    
			    <footer class="app-auth-footer">
				    <div class="container text-center py-3">
				       
			        <small class="copyright">Developed by Samson Fukuzeya <i class="fas fa-heart" style="color: #fb866a;"></i> @msuas 2022 projects</small>
				       
				    </div>
			    </footer><!--//app-auth-footer-->	
		    </div><!--//flex-column-->   
	    </div><!--//auth-main-col-->    
    </div><!--//row-->
</body>
</html> 

templates/accounts/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en"> 
<head>
    <title>MSUAS | Sign In</title>
    
    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <meta name="description" content="Examination Scheduling System">
    <meta name="author" content="Samson Fukuzeya">    
    
    <!-- FontAwesome JS-->
    <script defer src="{% static 'assets/plugins/fontawesome/js/all.min.js' %}"></script>
    
    <!-- App CSS -->  
    <link id="theme-style" rel="stylesheet" href="{% static 'assets/css/portal.css' %}">

</head> 

<body class="app app-login p-0" style="background-color: rgba(243, 235, 235, 0.651);">    	
    <div class="row g-0 app-auth-wrapper" style="background-color: rgba(65, 70, 96, 0.389);">
	    <div class="col-12 col-md-12 col-lg-12 auth-main-col text-center p-5">
		    <div class="d-flex flex-column align-content-end">
			    <div class="app-auth-body mx-auto">	
				    <div class="app-auth-branding mb-4"><a class="app-logo" href="/"><img class="logo-icon me-2" src="{% static 'logo-icon.png' %}" alt="logo"></a></div>
					<h2 class="auth-heading text-center mb-5">Log in to Portal</h2>
			        <div class="auth-form-container text-start">
						{% if form.errors %}
                        <h4 class="alert alert-danger">Wrong password or username!</h4>
                        {% for field in form %}
                        {% if field.errors %}
                        <div class="alert alert-box alert-danger" role="alert">
                            <h3>Wrong username or Password!</h3>
                        </div>
                        {% endif %}
                        {% endfor %}
                        {% endif %}
						{% if messages %}
                            {% for message in messages %}
                            {% if message.tags == 'error' %}
                            <div class="alert alert-danger" style="margin-top:10px">{{ message }}</div>
                            {% endif %}
                            {% if message.tags == 'success' %}
                            <div class="alert alert-success" style="margin-top:10px">{{ message }}</div>
                            {% endif %}
                            {% endfor %}
                          {% endif %}
						<form class="auth-form login-form" method="post">{% csrf_token %}         
							<div class="email mb-3">
								<label class="sr-only" for="signup-email">Your EC Number</label>
								{{form.username}}
							</div>
							<div class="password mb-3">
								<label class="sr-only" for="signup-password">Password</label>
								{{form.password}}
							</div>
								<div class="extra mt-3 row justify-content-between">
									<div class="col-6">
										<div class="form-check">
											<input class="form-check-input" type="checkbox" value="" id="RememberPassword">
											<label class="form-check-label" for="RememberPassword">
											Remember me
											</label>
										</div>
									</div><!--//col-6-->
									<div class="col-6">
										<div class="forgot-password text-end">
											<a href="#">Forgot password?</a>
										</div>
									</div><!--//col-6-->
								</div><!--//extra-->
							</div><!--//form-group-->
							<div class="text-center">
								<button type="submit" class="btn app-btn-primary w-100 theme-btn mx-auto">Log In</button>
							</div>
						</form>
						
						<div class="auth-option text-center pt-5">No Account? Sign up <a class="text-link" href="{% url 'accounts:register_account' %}" >here</a>.</div>
					</div><!--//auth-form-container-->	

			    </div><!--//auth-body-->
		    
			    <footer class="app-auth-footer">
				    <div class="container text-center py-3">
				       
			        <small class="copyright">Developed by Samson Fukuzeya <i class="fas fa-heart" style="color: #fb866a;"></i> @msuas 2022 projects</small>
				       
				    </div>
			    </footer><!--//app-auth-footer-->	
		    </div><!--//flex-column-->   
	    </div><!--//auth-main-col-->    
    </div><!--//row-->
</body>
</html> 

templates/accounts/student-login.html
{% load static %}
<!DOCTYPE html>
<html lang="en"> 
<head>
    <title>MSUAS | Sign In</title>
    
    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <meta name="description" content="Examination Scheduling System">
    <meta name="author" content="Samson Fukuzeya">    
    
    <!-- FontAwesome JS-->
    <script defer src="{% static 'assets/plugins/fontawesome/js/all.min.js' %}"></script>
    
    <!-- App CSS -->  
    <link id="theme-style" rel="stylesheet" href="{% static 'assets/css/portal.css' %}">

</head> 

<body class="app app-login p-0" style="background-color: rgba(168, 28, 28, 0.651);">    	
    <div class="row g-0 app-auth-wrapper">
	    <div class="col-12 col-md-12 col-lg-12 auth-main-col text-center p-5">
		    <div class="d-flex flex-column align-content-end">
			    <div class="app-auth-body mx-auto">	
				    <div class="app-auth-branding mb-4"><a class="app-logo" href="/"><img class="logo-icon me-2" src="{% static 'logo-icon.png' %}" alt="logo"></a></div>
					<h2 class="auth-heading text-center mb-5">Log in to Portal</h2>
			        <div class="auth-form-container text-start">
						{% if form.errors %}
                        <h4 class="alert alert-danger">Wrong password or username!</h4>
                        {% for field in form %}
                        {% if field.errors %}
                        <div class="alert alert-box alert-danger" role="alert">
                            <h3>Wrong username or Password!</h3>
                        </div>
                        {% endif %}
                        {% endfor %}
                        {% endif %}
						{% if messages %}
                            {% for message in messages %}
                            {% if message.tags == 'error' %}
                            <div class="alert alert-danger" style="margin-top:10px">{{ message }}</div>
                            {% endif %}
                            {% if message.tags == 'success' %}
                            <div class="alert alert-success" style="margin-top:10px">{{ message }}</div>
                            {% endif %}
                            {% endfor %}
                          {% endif %}
						<form class="auth-form login-form" method="post">{% csrf_token %}         
							<div class="email mb-3">
								<label class="sr-only" for="signup-email">Your EC Number</label>
								{{form.username}}
							</div>
							<div class="password mb-3">
								<label class="sr-only" for="signup-password">Password</label>
								{{form.password}}
							</div>
								<div class="extra mt-3 row justify-content-between">
									<div class="col-6">
										<div class="form-check">
											<input class="form-check-input" type="checkbox" value="" id="RememberPassword">
											<label class="form-check-label" for="RememberPassword">
											Remember me
											</label>
										</div>
									</div><!--//col-6-->
									<div class="col-6">
										<div class="forgot-password text-end">
											<a href="reset-password.html">Forgot password?</a>
										</div>
									</div><!--//col-6-->
								</div><!--//extra-->
							</div><!--//form-group-->
							<div class="text-center">
								<button type="submit" class="btn app-btn-primary w-100 theme-btn mx-auto">Log In</button>
							</div>
						</form>
						
						<div class="auth-option text-center pt-5">No Account? Sign up <a class="text-link" href="{% url 'accounts:student_signup' %}" >here</a>.</div>
					</div><!--//auth-form-container-->	

			    </div><!--//auth-body-->
		    
			    <footer class="app-auth-footer">
				    <div class="container text-center py-3">
				       
			        <small class="copyright">Developed by Samson Fukuzeya <i class="fas fa-heart" style="color: #fb866a;"></i> @msuas 2022 projects</small>
				       
				    </div>
			    </footer><!--//app-auth-footer-->	
		    </div><!--//flex-column-->   
	    </div><!--//auth-main-col-->    
    </div><!--//row-->
</body>
</html> 