Accounts/urls.py
import profile
from django.urls import path
from .views import *



app_name = 'accounts'

urlpatterns =[
    path('home/',home, name='home_page'),
    path('users/auth/register/account/',register_User, name='register_account'),
    path('users/hod/auth/register/account/',register_Hod, name='register_hod_account'),
    path('verify/',verify_view, name='verify_user'),
    path('login/', auth_view, name='login'),
    path('hod/login/', hod_auth_view, name='hod_login'),
    path('user/profile/entry/',profile_entry, name='user_profile'),
    path('student/auth/login/', student_auth_view, name="student_login"),
    path('student/auth/signup/',register_Student, name="student_signup"),
    
]

Exam_Scheduling_System/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Management.urls',namespace='management')),
    path('scheduling/',include('Scheduling.urls',namespace='scheduling')),
    path('accounts/',include('Accounts.urls',namespace='accounts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Scheduling/urls.py
from django.urls import path
from .views import *


app_name='scheduling'

urlpatterns =[
    path('status/', has_scheduling, name="scheduling_alg"),
    path('add/session/',add_session, name='exam_session'),
    path('simulation/',simulate_scheduling, name='simulation'),
    path('view/timetable/',get_timetable, name='get_timetable'),
    path('exam/reschedule/',reschedule_exams, name='exam_reschedule'),
    path('rescheduling/',individual_timetable_reschedule, name='reschedule'),
    path('room/allocation/report/',get_timetable_report,name='room_report'),
    path('timetable/pdf',get_timetable_pdf, name='timetable_pdf'),

]

templates/index.html
<!doctype html>{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Home | MSUAS | Examination Timetable</title>
    <link rel="shortcut icon" href="{% static 'assets/images/fav.png' %}" type="image/x-icon">
    <link href="{% static 'https://fonts.googleapis.com/css2?family=Work+Sans:wght@300;400;500;600;700&display=swap' %} " rel="stylesheet">
    <link rel="shortcut icon" href="{% static 'home/assets/images/fav-icon.png' %}">
    <link rel="stylesheet" href="{% static 'home/assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'home/assets/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'home/assets/css/style.css' %}" />
    <link rel="stylesheet" href="{% static 'home/assets/css/responsive.css' %}" />
</head>

<body style="background-color: rgb(176, 180, 198);">
    <!-- ===============================*****Start Header*****=============================== -->
    <header>
        <div class="top-nav">
            <div class="container">
                <div class="row">
                    <div class="col-md-4 col-12">
                        <div class="logo">
                            <h1>MSUAS</h1>
                        </div>
                    </div>
                    <div class="col-md-8 col-12">
                        <div class="top-sec-main">
                           <div class="top-sec">
                                <ol>
                                    <li>
                                        <i class="far fa-clock"></i>
                                        <span>Open on mon-fri</span>8:00-16:45
                                    </li>
                                    <li>
                                        <i class="fa fa-headphones"></i>
                                        <span>call for consultation</span>077 808 1286
                                    </li>
                                </ol>
                            </div>
                            <div class="top-sec-2">
                                <ol>
                                    <li><i class="fab fa-facebook-square"></i></li>
                                    <li><i class="fab fa-twitter"></i></li>
                                    <li class="last"><i class="fas fa-search"></i></li>
                                </ol>
                            </div> 
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="_main_nav" style="background-color: rgb(209, 47, 42);">
            <div class="container">
                <div class="row">
                    <div class="nav">
                        <div class="logo-01">
                            <h1>MSUAS</h1>
                        </div>
                        <div class="menu-toggle"></div>
                        <div class="my-nav">
                            <div class="menu">
                              <ul>
                                <li><a href="/">Home</a></li>
                                <li><a href="#">About Us</a></li>
                                <li><a href="#">Services</a></li>
                                <li><a href="#">Notice</a></li>
                                <li><a href="#">Contact Us</a></li>
                                <!-- <li class="link-01"><a href="{% url 'admin:index' %}">Staff Login</a></li> -->
                              </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- ===============================*****End Header*****=============================== -->

    <!-- ===============================*****Start Slider*****=============================== -->

    <section class="slider" style="background-color: rgb(103, 103, 218);">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="slider-content-main">
                        <ol>
                            <li><img src="{% static 'home/assets/images/zimbabwe-flag-round.gif' %}"></li>
                        </ol>
                        <h2>MANICALAND STATE UNIVERSITY OF APPLIED SCIENCES</h2>
                        <h2 style="text-align:center">Examination Timetable</h2>
                        <p>Examination Timetable<span>-</span>Exam Timetable queries<span>-</span></p>
                        <div class="btn-01">
                            <a href="{% url 'accounts:student_login' %}">Student Portal</a>
                            <a href="{% url 'accounts:login' %}">Staff Portal</a>
                            <a href="{% url 'accounts:hod_login' %}">H.O.D Portal</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="bg-02">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="headding-01">
                        <!-- <i class="fas fa-landmark"></i> -->
                        <h2>Exam Department Staff Members</h2>
                        <p></p>
                    </div>
                </div>
            </div>
            <div class="row">
            <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12" style="border-radius: 2%;">
                <div class="big-client" style="border-radius: 2%;">
                    <div class="client" style="border-radius: 2%;">
                        <img src="{% static 'home/assets1/img/default.png' %}">
                    </div>
                    <div class="client-content">
                        <h2>Miss Japu</h2>
                        <p>Administator</p>
                    </div>
                </div>
            </div>
            
            <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                <div class="big-client">
                    <div class="client">
                        <img src="{% static 'home/assets1/img/default.png' %}">
                    </div>
                    <div class="client-content">
                        <h2>Ms Cleo</h2>
                        <p>Administator</p>
                    </div>
                </div>
            </div>

            <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                <div class="big-client">
                    <div class="client">
                        <img src="{% static 'home/assets1/img/default.png' %}">
                    </div>
                    <div class="client-content">
                        <h2>S Fukuzeya</h2>
                        <p>Staff</p>
                    </div>
                </div>
            </div>            
            </div>
        </div>
    </section>

    <!-- <section class="bg-03">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                    <div class="box-01">
                        <ol>
                            <li><i class="fas fa-laptop"></i><span>Asset Registration</span>We register laptops,mouse, printers,keyboards,monitors...</li>
                            <li><i class="fab fa-critical-role"></i><span>Inventory Management</span>We manage information about collage computers and printers.</li>
                           
                        </ol>
                    </div>
                </div>

                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                    <div class="box-01">
                        <ol>
                            <li><i class="fas fa-cog"></i><span>Maintenance</span>We fix and repair staff and students laptop</li>
                            <li><i class="fas fa-network-wired"></i><span>Network Troubleshooting</span>We troubleshoot Wi-fi connection issues.</li>
                        </ol>
                    </div>
                </div>

                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                    <div class="box-01">
                        <ol>
                            <li><i class="fas fa-wifi-2"></i><span>Wi-Fi Accounts</span>We create wi-fi accounts for students.</li>
                            <li><i class="fab fa-laptop"></i><span>Help Desk</span>We respond to phone call quiries</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </section> -->

    <!-- <section class="bg-02-b">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-3 col-6">
                    <div class="cal-box">
                        <div class="cal-content">
                            <i class="fas fa-laptop"></i>
                            <h2>497</h2>
                            <h3>Registered Laptops</h3>
                        </div>
                    </div>
                </div>

                <div class="col-lg-3 col-md-3 col-6">
                    <div class="cal-box">
                        <div class="cal-content">
                            <i class="fas fa-laptop"></i>
                            <h2>2000</h2>
                            <h3>Wi-Fi Accounts</h3>
                        </div>
                    </div>
                </div>

                <div class="col-lg-3 col-md-3 col-6">
                    <div class="cal-box">
                        <div class="cal-content">
                            <i class="fas fa-laptop"></i>
                            <h2>120</h2>
                            <h3>Desktop in Labs</h3>
                        </div>
                    </div>
                </div>

                <div class="col-lg-3 col-md-3 col-6">
                    <div class="cal-box">
                        <div class="cal-content">
                            <i class="fas fa-laptop"></i>
                            <h2>15</h2>
                            <h3>Available Printers</h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section> -->

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-4 col-sm-6 col-xs-6">
                    <div class="footer-content">
                        <p>Manicaland State University Of Applied Sciences | Exam Timetable</p>
                        <ol>
                            <li><i class="fab fa-facebook-square"></i></li>
                            <li><i class="fab fa-pinterest"></i></li>
                            <li><i class="fab fa-instagram"></i></li>
                            <li><i class="fab fa-twitter"></i></li>
                        </ol>
                    </div>
                </div>

                <div class="col-lg-3 col-md-4 col-sm-6 col-xs-6">
                    
                     
                </div>

                <div class="col-lg-3 col-md-4 col-sm-6 col-xs-6">
                    
                </div>

                <div class="col-lg-3 col-md-4 col-sm-6 col-xs-6">
                    
                </div>
                <div class="col-lg-8 col-md-8 col-12">
                    
                </div>
                <div class="col-lg-4 col-md-4 col-12">
                    <div class="end-items-01">
                        <ul>
                            <li><span>copyright@2022</span>Samson Fukuzeya.</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </footer>
</body>

<script src="{% static 'home/assets/js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'home/assets/js/popper.min.js' %}"></script>
<script src="{% static 'home/assets/js/bootstrap.min.js' %}"></script>
<script>
      $(document).ready (function(){
        $('.menu-toggle').click(function(){
          $('.menu-toggle').toggleClass('active')
          $('.menu').toggleClass('active')
        })
      })
</script>
</html>

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en"> 
<head>
    <title>MSUAS | Sign In</title>
    
    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <meta name="description" content="Examination Scheduling System">
    <meta name="author" content="Samson Fukuzeya">    
    
    <!-- FontAwesome JS-->
    <script defer src="{% static 'assets/plugins/fontawesome/js/all.min.js' %}"></script>
    
    <!-- App CSS -->  
    <link id="theme-style" rel="stylesheet" href="{% static 'assets/css/portal.css' %}">

</head> 

<body class="app app-login p-0">    	
    <div class="row g-0 app-auth-wrapper">
	    <div class="col-12 col-md-12 col-lg-12 auth-main-col text-center p-5">
		    <div class="d-flex flex-column align-content-end">
			    <div class="app-auth-body mx-auto">	
				    <div class="app-auth-branding mb-4"><a class="app-logo" href="/"><img class="logo-icon me-2" src="{% static 'assets/images/app-logo.svg' %}" alt="logo"></a></div>
					<h2 class="auth-heading text-center mb-5">Log in to Portal</h2>
			        <div class="auth-form-container text-start">
						{% if form.errors %}
                        <h4 class="alert alert-danger">Wrong password or username!</h4>
                        {% for field in form %}
                        {% if field.errors %}
                        <div class="alert alert-box alert-danger" role="alert">
                            <h3>Wrong username or Password!</h3>
                        </div>
                        {% endif %}
                        {% endfor %}
                        {% endif %}
						<form class="auth-form login-form" method="post">{% csrf_token %}         
							<div class="email mb-3">
								<label class="sr-only" for="signin-email">Username</label>
								{{form.username}}
							</div><!--//form-group-->
							<div class="password mb-3">
								<label class="sr-only" for="signin-password">Password</label>
								{{form.password}}
								<div class="extra mt-3 row justify-content-between">
									<div class="col-6">
										<div class="form-check">
											<input class="form-check-input" type="checkbox" value="" id="RememberPassword">
											<label class="form-check-label" for="RememberPassword">
											Remember me
											</label>
										</div>
									</div><!--//col-6-->
									<div class="col-6">
										<div class="forgot-password text-end">
											<a href="reset-password.html">Forgot password?</a>
										</div>
									</div><!--//col-6-->
								</div><!--//extra-->
							</div><!--//form-group-->
							<div class="text-center">
								<button type="submit" class="btn app-btn-primary w-100 theme-btn mx-auto">Log In</button>
							</div>
						</form>
						
						<div class="auth-option text-center pt-5">No Account? Sign up <a class="text-link" href="{% url 'accounts:register_account' %}" >here</a>.</div>
					</div><!--//auth-form-container-->	

			    </div><!--//auth-body-->
		    
			    <footer class="app-auth-footer">
				    <div class="container text-center py-3">
				       
			        <small class="copyright">Developed by Samson Fukuzeya <i class="fas fa-heart" style="color: #fb866a;"></i> @msuas 2022 projects</small>
				       
				    </div>
			    </footer><!--//app-auth-footer-->	
		    </div><!--//flex-column-->   
	    </div><!--//auth-main-col-->    
    </div><!--//row-->
</body>
</html> 

templates/simulation.html
{% load static %}
<!DOCTYPE html>
<!-- Created By CodingNepal -->
<html lang="en" dir="ltr">
   <head>
      <meta charset="utf-8">
      <title>MSUAS|Exam Scheduling|Processing...</title>
      <link rel="stylesheet" href="{% static 'style3.css' %}">
   </head>
   <body>
      <div class="container" style="background-image: url(../static/Capture.PNG);">
         <div class="wrapper">
            <div class="loader">
               <div class="dot"></div>
            </div>
            <div class="loader">
               <div class="dot"></div>
            </div>
            <div class="loader">
               <div class="dot"></div>
            </div>
            <div class="loader">
               <div class="dot"></div>
            </div>
            <div class="loader">
               <div class="dot"></div>
            </div>
            <div class="loader">
               <div class="dot"></div>
            </div>
         </div>
         <div class="text">
           <a id="schedule" href="{% url 'scheduling:get_timetable' %}" style="text-decoration:none ; color: aliceblue; font-weight: bolder;"> Scheduling Started please wait...</a>

         </div>
      </div>
   </body>
   <script src="{% static 'jquery-3.6.0.min.js' %}" ></script>
   <script type='text/javascript'>
       $(document).ready(function(){
               $.ajax({
                   type: "GET",
                   cache: false,
                   url: "/scheduling/status/",
                   dataType: "json",
                   success: function(data) {
                       var msg = $('#schedule').text('Scheduling Started please wait...')
                       $('#schedule').append(msg)
                       var i = 0;
                       var threadInterval = setInterval(function(){

                           checkTask("/scheduling/status/", function(check){
                               if(check.id){
                                   msg.text('Algorithm done scheduling. View Timetable')
                                   
                                   pageRedirect();
                                   
                                //    window.location.href("/scheduling/view/timetable/")

                                 //   redirect("/scheduling/view/timetable/")
                                   window.clearInterval(threadInterval)
                               }
                               if(++i === 30){
                                   msg.text('Its taking longer than expected...please keep waiting.')
                                   window.clearInterval(threadInterval)
                               }
                           })
                       },1000)
                   }
               })
           

           function checkTask(url,cb){
               $.ajax({
                   type: "GET",
                   cache: false,
                   url: url,
                   dataType: "json",
                   success: function(data) {
                       cb(data)
                   }
               })
           }
           function redirect(url){
               $.ajax({
                   type: "GET",
                   cache: false,
                   url: url,
                   dataType: "json",
                   success: function(data) {
                       cb(data)
                   }
               })
           }
         })
         function pageRedirect() {
      window.location.href = "/scheduling/view/timetable/";
    } 
         
   </script>
</html>