Accounts/urls.py
import profile
from django.urls import path
from .views import *



app_name = 'accounts'

urlpatterns =[
    path('home/',home, name='home_page'),
    path('users/auth/register/account/',register_User, name='register_account'),
    path('users/hod/auth/register/account/',register_Hod, name='register_hod_account'),
    path('verify/',verify_view, name='verify_user'),
    path('login/', auth_view, name='login'),
    path('hod/login/', hod_auth_view, name='hod_login'),
    path('user/profile/entry/',profile_entry, name='user_profile'),
    path('student/auth/login/', student_auth_view, name="student_login"),
    path('student/auth/signup/',register_Student, name="student_signup"),
    
]

Exam_Scheduling_System/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Management.urls',namespace='management')),
    path('scheduling/',include('Scheduling.urls',namespace='scheduling')),
    path('accounts/',include('Accounts.urls',namespace='accounts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Management/urls.py
from django.urls import path
from .views import *


app_name='management'

urlpatterns =[
    path('', home_page, name="home"),
    path('departments/',get_all_departments, name='get_departments'),
    path('programmes/',get_all_programmes, name='get_programmes'),
    path('modules/',get_all_modules, name='get_modules'),
    path('exam/rooms/',get_all_exam_rooms, name='get_exam_rooms'),
    path('invigilators/',get_all_invigilators, name='get_invigilators'),
    path('registration/',get_registration_information, name='get_registration_info'),
    path('department/timetable/',get_department_timetable, name='department_timetable'),
    path('student/profile/',student_profile, name="student_prof"),
    path('student/timetable/',get_student_time_table, name='student_timetable'),
    path('accounts/auth/signup/',signup, name='account_signup'),
    path('program/timetable/<int:id>/', get_program_timetable, name="program_timetable"),
    path('student/registered/modules/',student_modules, name='student_registered_modules'),
    path('timetable/pdf/',generate_module_pdf,name="module_pdf"),
    path('generate/pdf/',export_pdf, name='get_pdf'),
    path('invigilator/assignment/',assign_invigilators,name='assign_invigilator'),
    path('allocate/seatingposition/',allocate_seating_position,name='seating_position'),
    path('department/timetable/pdf/',get_department_timetable_pdf,name='department_pdf'),
    path('student/timetable/pdf/',get_student_time_table_pdf,name='student_pdf'),
]

templates/hod/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en"> 
<head>
    <title>MSUAS | Department</title>
    
    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <meta name="description" content="MSUAS EXAMINATION SCHEDULING SYSTEM">
    <meta name="author" content="msuas">        
    <!-- FontAwesome JS-->
    <script defer src="{% static 'assets/plugins/fontawesome/js/all.min.js' %}"></script>
    
    <!-- App CSS -->  
    <link id="theme-style" rel="stylesheet" href="{% static 'assets/css/portal.css' %}">

</head> 

<body class="app">   	
    <header class="app-header fixed-top" style="border-radius: 2%; background-color: brown;">	   	            
        <div class="app-header-inner">  
	        <div class="container-fluid py-2">
		        <div class="app-header-content"> 
		            <div class="row justify-content-between align-items-center">
			        
				    <div class="col-auto">
					    <a id="sidepanel-toggler" class="sidepanel-toggler d-inline-block d-xl-none" href="#">
						    <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 30 30" role="img"><title>Menu</title><path stroke="currentColor" stroke-linecap="round" stroke-miterlimit="10" stroke-width="2" d="M4 7h22M4 15h22M4 23h22"></path></svg>
					    </a>
				    </div><!--//col-->
		            <div class="search-mobile-trigger d-sm-none col">
			            <i class="search-mobile-trigger-icon fas fa-search"></i>
			        </div><!--//col-->
		            
		            
		            <div class="app-utilities col-auto">
			            <div class="app-utility-item app-notifications-dropdown dropdown">    
				            
					        <div class="dropdown-menu p-0" aria-labelledby="notifications-dropdown-toggle">
					            
						        <div class="dropdown-menu-content">
							       <div class="item p-3">
								        <div class="row gx-2 justify-content-between align-items-center">
									        <div class="col-auto">
										       
									        </div><!--//col-->
									        <div class="col">
										        <div class="info"> 
											        <div class="desc"></div>
											        <div class="meta"></div>
										        </div>
									        </div><!--//col--> 
								        </div><!--//row-->
								        <a class="link-mask" href="#"></a>
							       </div><!--//item-->
							       <div class="item p-3">
								        <div class="row gx-2 justify-content-between align-items-center">
									        <div class="col-auto">
										        <div class="app-icon-holder">
											        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-receipt" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
	  <path fill-rule="evenodd" d="M1.92.506a.5.5 0 0 1 .434.14L3 1.293l.646-.647a.5.5 0 0 1 .708 0L5 1.293l.646-.647a.5.5 0 0 1 .708 0L7 1.293l.646-.647a.5.5 0 0 1 .708 0L9 1.293l.646-.647a.5.5 0 0 1 .708 0l.646.647.646-.647a.5.5 0 0 1 .708 0l.646.647.646-.647a.5.5 0 0 1 .801.13l.5 1A.5.5 0 0 1 15 2v12a.5.5 0 0 1-.053.224l-.5 1a.5.5 0 0 1-.8.13L13 14.707l-.646.647a.5.5 0 0 1-.708 0L11 14.707l-.646.647a.5.5 0 0 1-.708 0L9 14.707l-.646.647a.5.5 0 0 1-.708 0L7 14.707l-.646.647a.5.5 0 0 1-.708 0L5 14.707l-.646.647a.5.5 0 0 1-.708 0L3 14.707l-.646.647a.5.5 0 0 1-.801-.13l-.5-1A.5.5 0 0 1 1 14V2a.5.5 0 0 1 .053-.224l.5-1a.5.5 0 0 1 .367-.27zm.217 1.338L2 2.118v11.764l.137.274.51-.51a.5.5 0 0 1 .707 0l.646.647.646-.646a.5.5 0 0 1 .708 0l.646.646.646-.646a.5.5 0 0 1 .708 0l.646.646.646-.646a.5.5 0 0 1 .708 0l.646.646.646-.646a.5.5 0 0 1 .708 0l.646.646.646-.646a.5.5 0 0 1 .708 0l.509.509.137-.274V2.118l-.137-.274-.51.51a.5.5 0 0 1-.707 0L12 1.707l-.646.647a.5.5 0 0 1-.708 0L10 1.707l-.646.647a.5.5 0 0 1-.708 0L8 1.707l-.646.647a.5.5 0 0 1-.708 0L6 1.707l-.646.647a.5.5 0 0 1-.708 0L4 1.707l-.646.647a.5.5 0 0 1-.708 0l-.509-.51z"/>
	  <path fill-rule="evenodd" d="M3 4.5a.5.5 0 0 1 .5-.5h6a.5.5 0 1 1 0 1h-6a.5.5 0 0 1-.5-.5zm0 2a.5.5 0 0 1 .5-.5h6a.5.5 0 1 1 0 1h-6a.5.5 0 0 1-.5-.5zm0 2a.5.5 0 0 1 .5-.5h6a.5.5 0 1 1 0 1h-6a.5.5 0 0 1-.5-.5zm0 2a.5.5 0 0 1 .5-.5h6a.5.5 0 0 1 0 1h-6a.5.5 0 0 1-.5-.5zm8-6a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 0 1h-1a.5.5 0 0 1-.5-.5zm0 2a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 0 1h-1a.5.5 0 0 1-.5-.5zm0 2a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 0 1h-1a.5.5 0 0 1-.5-.5zm0 2a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 0 1h-1a.5.5 0 0 1-.5-.5z"/>
	</svg>
										        </div>
									        </div><!--//col-->
									        <div class="col">
										        
									        </div><!--//col-->
								        </div><!--//row-->
								        <a class="link-mask" href="#"></a>
							       </div><!--//item-->
						        </div><!--//dropdown-menu-content-->
						        
						        <div class="dropdown-menu-footer p-2 text-center">
							        <a href="#"></a>
						        </div>
															
							</div><!--//dropdown-menu-->					        
				        </div><!--//app-utility-item-->
			            <div class="app-utility-item app-user-dropdown dropdown">
				            <a class="dropdown-toggle" id="user-dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">{{request.user.username}}</a>
				            <ul class="dropdown-menu" aria-labelledby="user-dropdown-toggle">
								
								<li><a class="dropdown-item" href="{% url 'accounts:hod_login' %}">Log Out</a></li>
							</ul>
			            </div><!--//app-user-dropdown--> 
		            </div><!--//app-utilities-->
		        </div><!--//row-->
	            </div><!--//app-header-content-->
	        </div><!--//container-fluid-->
        </div><!--//app-header-inner-->
        <div id="app-sidepanel" class="app-sidepanel" style="border-radius: 2%; background-color: brown;"> 
	        <div id="sidepanel-drop" class="sidepanel-drop"></div>
	        <div class="sidepanel-inner d-flex flex-column" style="border-radius: 2%; background-color: brown;">
		        <a href="#" id="sidepanel-close" class="sidepanel-close d-xl-none">&times;</a>
		        <div class="app-branding">
		            <a class="app-logo" href="#"><img class="logo-icon me-2" src="{% static 'logo-icon.png' %}" alt="logo"><span class="logo-text">H.O.D Portal</span></a>
		        </div><!--//app-branding-->  
		        
			    <nav id="app-nav-main" class="app-nav app-nav-main flex-grow-1" style="border-radius: 2%; background-color: brown;">
				    <ul class="app-menu list-unstyled accordion" id="menu-accordion" style="border-radius: 2%; background-color: rgb(99, 52, 52);">
					    <li class="nav-item">
					       
					        <a class="nav-link" href="#">
						        <span class="nav-icon">
						        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-house-door" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
		  <path fill-rule="evenodd" d="M7.646 1.146a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 .146.354v7a.5.5 0 0 1-.5.5H9.5a.5.5 0 0 1-.5-.5v-4H7v4a.5.5 0 0 1-.5.5H2a.5.5 0 0 1-.5-.5v-7a.5.5 0 0 1 .146-.354l6-6zM2.5 7.707V14H6v-4a.5.5 0 0 1 .5-.5h3a.5.5 0 0 1 .5.5v4h3.5V7.707L8 2.207l-5.5 5.5z"/>
		  <path fill-rule="evenodd" d="M13 2.5V6l-2-2V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5z"/>
		</svg>
						         </span>
		                         <span class="nav-link-text">Home</span>
					        </a><!--//nav-link-->
					    </li><!--//nav-item-->
					    <li class="nav-item" style="background-color:rgb(105, 105, 222) ;">
					        <a class="nav-link active" href="#">
						        <span class="nav-icon">
						        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-folder" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path d="M9.828 4a3 3 0 0 1-2.12-.879l-.83-.828A1 1 0 0 0 6.173 2H2.5a1 1 0 0 0-1 .981L1.546 4h-1L.5 3a2 2 0 0 1 2-2h3.672a2 2 0 0 1 1.414.586l.828.828A2 2 0 0 0 9.828 3v1z"/>
  <path fill-rule="evenodd" d="M13.81 4H2.19a1 1 0 0 0-.996 1.09l.637 7a1 1 0 0 0 .995.91h10.348a1 1 0 0 0 .995-.91l.637-7A1 1 0 0 0 13.81 4zM2.19 3A2 2 0 0 0 .198 5.181l.637 7A2 2 0 0 0 2.826 14h10.348a2 2 0 0 0 1.991-1.819l.637-7A2 2 0 0 0 13.81 3H2.19z"/>
</svg>
						         </span>
		                         <span class="nav-link-text">Timetable</span>
					        </a><!--//nav-link-->
					    </li><!--//nav-item-->
					    				    
				    </ul><!--//app-menu-->
			    </nav><!--//app-nav-->
			    
		       
	        </div><!--//sidepanel-inner-->
	    </div><!--//app-sidepanel-->
    </header><!--//app-header-->
    
    <div class="app-wrapper">
	    {% block body %}

		{% endblock body %}
	   
	    <footer class="app-footer">
		    <div class="container text-center py-3">
		        
            <small class="copyright">Developed by S.Fukuzeya <i class="fas fa-heart" style="color: #fb866a;"></i> @msuas 2022 Dessertation</small>
		       
		    </div>
	    </footer><!--//app-footer-->
	    
    </div><!--//app-wrapper-->    					

 
    <!-- Javascript -->          
    <script src="{% static 'assets/plugins/popper.min.js' %}"></script>
    <script src="{% static 'assets/plugins/bootstrap/js/bootstrap.min.js' %}"></script>  

    
    <!-- Page Specific JS -->
    <script src="{% static 'assets/js/app.js' %}"></script> 

</body>
</html> 

templates/hod/timetable.html
{% extends "./base.html" %}
{% load static %}
{% block body %}
    <div class="app-content pt-3 p-md-3 p-lg-4">
        <div class="container-xl">
            
            <div class="row g-3 mb-4 align-items-center justify-content-between">
                <div class="col-auto">
                    <h1 class="app-page-title mb-0">Department Examination Timetable</h1>
                </div>
                <div class="col-auto">
                     <div class="page-utilities">
                        <div class="row g-2 justify-content-start justify-content-md-end align-items-center">
                            <div class="col-auto">
                                <!-- <form class="table-search-form row gx-1 align-items-center">
                                    <div class="col-auto">
                                        <input type="text" id="search-orders" name="searchorders" class="form-control search-orders" placeholder="Search">
                                    </div>
                                    <div class="col-auto">
                                        <button type="submit" class="btn app-btn-secondary">Search</button>
                                    </div>
                                </form> -->
                                
                            </div><!--//col-->
                            <div class="col-auto">
                                <div class="app-utility-item dropdown">
                                    <a class="dropdown-toggle" id="user-dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Choose Program</a>
                                    <ul class="dropdown-menu" aria-labelledby="user-dropdown-toggle">
                                        <li><a class="dropdown-item" href="{% url 'management:department_timetable' %}">Department Timetable</a></li>
                                        {% for program in programes %}
                                        <li><a class="dropdown-item" href="{% url 'management:program_timetable' program.id %}">{{program.programme_name}}</a></li>
                                        <li><hr class="dropdown-divider"></li>
                                        {% endfor %}
                                    </ul>
                                </div>
                        
                                <!-- <select class="form-select w-auto" >
                                      <option selected value="option-1"><a role="button" href="{% url 'management:department_timetable' %}"> All</a></option>
                                      {% for program in programes %}
                                      <option value="{{forloop.counter}}"><a role="button" href="{% url 'management:program_timetable' program.id %}">{{program.programme_name}}</a></option>
                                      {% endfor %}
                                      
                                </select> -->
                            </div>
                            <div class="col-auto">						    
                                <a class="btn app-btn-secondary" href="{% url 'management:department_pdf' %}">
                                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-download me-1" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
      <path fill-rule="evenodd" d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z"/>
      <path fill-rule="evenodd" d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z"/>
    </svg>
                                    Download PDF
                                </a>
                            </div>
                        </div><!--//row-->
                    </div><!--//table-utilities-->
                </div><!--//col-auto-->
            </div><!--//row-->
           
            
            <nav id="orders-table-tab" class="orders-table-tab app-nav-tabs nav shadow-sm flex-column flex-sm-row mb-4">
                {% if program %}
                <a class="flex-sm-fill text-sm-center nav-link active" id="orders-all-tab" data-bs-toggle="tab" href="#orders-all" role="tab" aria-controls="orders-all" aria-selected="true">PROGRAMME: {{program}}</a>
                
                {% else %}
                <a class="flex-sm-fill text-sm-center nav-link active" id="orders-all-tab" data-bs-toggle="tab" href="#orders-all" role="tab" aria-controls="orders-all" aria-selected="true">DEPARTMENT OF {{department.department_name}}</a>
                {% endif %}

                <!-- {% for program in programes %}
                <a class="flex-sm-fill text-sm-center nav-link"  id="orders-paid-tab"  href="{% url 'management:program_timetable' program.id %}"  aria-controls="orders-paid" aria-selected="false">{{program.programme_name}}</a> 
                {% endfor %} -->
                <!-- <a class="flex-sm-fill text-sm-center nav-link" id="orders-pending-tab" data-bs-toggle="tab" href="#orders-pending" role="tab" aria-controls="orders-pending" aria-selected="false">Pending</a>
                <a class="flex-sm-fill text-sm-center nav-link" id="orders-cancelled-tab" data-bs-toggle="tab" href="#orders-cancelled" role="tab" aria-controls="orders-cancelled" aria-selected="false">Cancelled</a>  -->
            </nav>
            
            
            <div class="tab-content" id="orders-table-tab-content">
                <div class="tab-pane fade show active" id="orders-all" role="tabpanel" aria-labelledby="orders-all-tab">
                    <div class="app-card app-card-orders-table shadow-sm mb-5">
                        <div class="app-card-body">
                            <div class="table-responsive">
                                <table class="table app-table-hover mb-0 text-left">
                                    <thead>
                                        <tr>
                                            <th class="cell">Date</th>
                                            <th class="cell">Module</th>
                                            <th class="cell">Title</th>
                                            <th class="cell">Students</th>
                                            <th class="cell">Venue</th>
                                            <th class="cell">Time</th>
                                            
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for slot in timetables %}
                                        <tr>
                                            <td class="cell">{{slot.date}}</td>
                                            <td class="cell">{{slot.module}}</td>
                                            <td class="cell">{{slot.title}}</td>
                                            <td class="cell">{{slot.students}}</td>
                                            <td class="cell">{{slot.room}}</td>
                                            <td class="cell"><span>{{slot.time}}</span></td>
                                        </tr>
                                        {% empty %}
                                        <h4>No timetable generated yet.</h4>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div><!--//table-responsive-->
                           
                        </div><!--//app-card-body-->		
                    </div><!--//app-card-->
                    <nav class="app-pagination">
                        <ul class="pagination justify-content-center">
                            <li class="page-item disabled">
                                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
                            </li>
                            <li class="page-item active"><a class="page-link" href="#">1</a></li>
                            <li class="page-item"><a class="page-link" href="#">2</a></li>
                            <li class="page-item"><a class="page-link" href="#">3</a></li>
                            <li class="page-item">
                                <a class="page-link" href="#">Next</a>
                            </li>
                        </ul>
                    </nav><!--//app-pagination-->
                </div><!--//tab-pane-->
            </div><!--//tab-content-->
        </div><!--//container-fluid-->
{% endblock body %}